services:
  signos-vitales-productor:
    image: ms-signos-vitales
    container_name: signos-vitales-productor
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "172.31.82.234:9092"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3"
    networks:
      - external_network

networks:
  external_network:
    driver: bridge
